name: Marcus Aurelius Travel Blog
favicon: null
layout_spectrum: 0.28653758415021
typography_spectrum: 0.8227762070018798
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5408411798998713
  lightness: 0.8620392570737749
  saturation: 0.025518517708405852
  rhythmicContrast: 0.4338507717475295
purpose: []
