name: TravelingMAC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31017
title: A travel-blog by Marcus Aurelius
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25
  lightness: 0.8620392570737749
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
